### ISSUE TITLE
Error Report on Customer Login

### ISSUE THREAD

**Issue by unifiedarts** [magespecialist/m2-MSP_ReCaptcha#12]
hello,

we installed the extension and receive an error on customer login with blank captcha settings (checkbox not set). Error:

![bildschirmfoto 2017-09-01 um 13 00 47](https://user-images.githubusercontent.com/7428697/29967169-9e75c8f4-8f15-11e7-8f7d-b6e844825811.png)

Error Log:
```
a:4:{i:0;s:26:"Invalid HTTP response code";i:1;s:12727:"#0 ../htdocs/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(219): Magento\Framework\HTTP\PhpEnvironment\Response->setHttpResponseCode(Array)
#1 ../htdocs/vendor/magento/framework/HTTP/PhpEnvironment/Response.php(143): Magento\Framework\App\Response\Http\Interceptor->setHttpResponseCode(Array)
#2 ../htdocs/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(206): Magento\Framework\HTTP\PhpEnvironment\Response->setRedirect('https://www.wei...', Array)
#3 ../htdocs/vendor/msp/recaptcha/Observer/Frontend/LoginObserver.php(95): Magento\Framework\App\Response\Http\Interceptor->setRedirect('https://www.wei...', Array)
#4 ../htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): MSP\ReCaptcha\Observer\Frontend\LoginObserver->execute(Object(Magento\Framework\Event\Observer))
#5 ../htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(MSP\ReCaptcha\Observer\Frontend\LoginObserver), Object(Magento\Framework\Event\Observer))
#6 ../htdocs/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#7 ../htdocs/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#8 ../htdocs/vendor/magento/framework/App/Action/Action.php(95): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#9 ../htdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Account\LoginPost\Interceptor->___callParent('dispatch', Array)
#11 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Array, 'contextPlugin')
#12 ../htdocs/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Array, 'customer-app-ac...')
#15 ../htdocs/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#16 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Array, 'storeCheck')
#18 ../htdocs/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#19 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Array, 'customer_accoun...')
#21 ../htdocs/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Array, 'weee-app-action...')
#24 ../htdocs/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 ../htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Array, 'tax-app-action-...')
#27 ../htdocs/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Customer\Controller\Account\LoginPost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 ../htdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 ../htdocs/var/generation/Magento/Customer/Controller/Account/LoginPost/Interceptor.php(26): Magento\Customer\Controller\Account\LoginPost\Interceptor->___callPlugins('dispatch', Array, Array)
#30 ../htdocs/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\LoginPost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 ../htdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#33 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#34 ../htdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#35 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#37 ../htdocs/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#38 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#40 ../htdocs/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 ../htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#43 ../htdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
@
"var/report/243690687789" [noeol] 55L, 12869C
```

**Comment by phoenix128** [comment]
We were unable to reproduce this, can you please provide more information?

**Comment by phoenix128** [comment]
Closing for inactivity.

**Comment by Sanfam** [comment]
@phoenix128 , I've been able to reproduce this in some user scenarios on my end, log included below, and have also included steps to reproduce.  The issue appears related to submitting the form prematurely, without the recaptcha element loaded/present.

Requirements:
1. Access your site via Google Chrome
2. Ensure a valid username and password are saved in the browser's autocomplete feature and that these correctly populate on the login form

Actual Result:
1. Attempt to sign into your site with MSP reCaptcha enabled by visiting https://www.storedomain.com/customer/account/login/
2. As soon as the form appears, hit the "Sign In" button (note: the reCaptcha element will *not* yet have loaded)
3. Receive an Internal Server Error response, the log for which is detailed below

Expected Result:
1. Attempt to sign into your site with MSP reCaptcha enabled by visiting https://www.storedomain.com/customer/account/login/
2. As soon as the form appears, hit the "Sign In" button (note: the reCaptcha element will *not* yet have loaded)
3. Receive an on-page validation error indicating that the Captcha element must be completed in order to proceed

```
a:4:{i:0;s:26:"Invalid HTTP response code";i:1;s:12670:"#0 [redacted]/vendor/magento/framework/HTTP/PhpEnvironment/Response.php(143): Magento\Framework\HTTP\PhpEnvironment\Response->setHttpResponseCode(Array)
#1 [redacted]/vendor/msp/recaptcha/Observer/Frontend/LoginObserver.php(108): Magento\Framework\HTTP\PhpEnvironment\Response->setRedirect('https://www.who...', Array)
#2 [redacted]/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): MSP\ReCaptcha\Observer\Frontend\LoginObserver->execute(Object(Magento\Framework\Event\Observer))
#3 [redacted]/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(MSP\ReCaptcha\Observer\Frontend\LoginObserver), Object(Magento\Framework\Event\Observer))
#4 [redacted]/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#5 [redacted]/var/generation/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('controller_acti...', Array)
#6 [redacted]/vendor/magento/framework/App/Action/Action.php(95): Magento\Staging\Model\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#7 [redacted]/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(70): WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor->___callParent('dispatch', Array)
#9 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('WholeLatteLove\\...', 'dispatch', Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Array, 'contextPlugin')
#10 [redacted]/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('WholeLatteLove\\...', 'dispatch', Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Array, 'customer-segmen...')
#13 [redacted]/vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php(81): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch(Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('WholeLatteLove\\...', 'dispatch', Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Array, 'customer-app-ac...')
#16 [redacted]/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('WholeLatteLove\\...', 'dispatch', Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Array, 'storeCheck')
#19 [redacted]/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#20 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('WholeLatteLove\\...', 'dispatch', Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Array, 'customer_accoun...')
#22 [redacted]/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#23 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('WholeLatteLove\\...', 'dispatch', Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Array, 'weee-app-action...')
#25 [redacted]/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 [redacted]/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('WholeLatteLove\\...', 'dispatch', Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Array, 'tax-app-action-...')
#28 [redacted]/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 [redacted]/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 [redacted]/var/generation/WholeLatteLove/FirstCustomerAccess/Controller/Account/LoginPost/Interceptor.php(26): WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor->___callPlugins('dispatch', Array, Array)
#31 [redacted]/vendor/magento/framework/App/FrontController.php(55): WholeLatteLove\FirstCustomerAccess\Controller\Account\LoginPost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 [redacted]/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#33 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#34 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#35 [redacted]/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#38 [redacted]/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#39 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#41 [redacted]/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#42 [redacted]/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 [redacted]/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#44 [redacted]/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 [redacted]/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 [redacted]/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#47 [redacted]/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#48 [redacted]/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#49 [redacted]/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#50 {main}";s:3:"url";s:28:"/customer/account/loginPost/";s:11:"script_name";s:10:"/index.php";}
```
